import Head from 'next/head';
import Image from 'next/image';
import styles from 'src/styles/Home.module.css';
import { Footer } from 'src/components/Footer';
import { Main } from 'src/components/Main';
import { Facebooks } from 'src/components/Facebooks';
import { Header } from 'src/components/Header';
import { useCallback,useEffect } from 'react';

export default function Home() {
  const item = 1;

  const handleClick = useCallback( (e) => {
    console.log(e.target.href)
    e.preventDefault();
    alert(item);
  },[]);

  useEffect(() =>{
    console.log("マウント時");
    document.body.style.backgroundColor = "lightblue";

    return ()=>{
      console.log("アンマウント時");
      document.body.style.backgroundColor = "";
    }
  },[]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Study Index</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <a href="/about" onClick={handleClick}>ボタン</a>

      <Main page="index"></Main>
      {/* <Facebooks /> */}
      <Footer />

    </div>
  );
}
