import Head from 'next/head';
import Image from 'next/image';
import styles from 'src/styles/Home.module.css';
import { Footer } from 'src/components/Footer';
import { Main } from 'src/components/Main';
import { Facebooks } from 'src/components/Facebooks';
import { Header } from 'src/components/Header';
import { useEffect, useState, useCallback } from 'react';

export default function Home() {
  //配列分割代入
  const [item, setItem] = useState(1);
  const [text, setText] = useState("");
  const [isShow, setIsShow] = useState(true);
  const [array, setArray] = useState([]);

  const handleClick = useCallback(() => {
    if (item < 10) {
      setItem((previtem) => previtem + 1);
    }
    // setItem((item) => item +1);
  }, [item]);

  const handleDisplay = useCallback(() => {
    setIsShow((previsShow) => !previsShow);
  }, []);

  const handleChange = useCallback((e) => {
    if (e.target.value.length > 5) {
      alert("error");
      return;
    }
    setText(e.target.value.trim());
  }, []);

  const handleAdd = useCallback(() => {
    setArray((prevArray) => {
      if(prevArray.some((item)=> item === text)){
        alert("same");
        return prevArray;
      }
      return [...prevArray,text];
    });
  }, [text]);

  useEffect(() => {
    // console.log("マウント時");
    document.body.style.backgroundColor = "lightblue";

    return () => {
      // console.log("アンマウント時");
      document.body.style.backgroundColor = "";
    }
  }, []);



  return (
    <div className={styles.container}>
      <Head>
        <title>Study Index</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      {isShow ? <h1>{item}</h1> : null}

      <button onClick={handleClick}>ボタン</button>
      <button onClick={handleDisplay}>{isShow ? "非表示" : "表示"}</button>
      <input type="text" value={text} onChange={handleChange} />
      <button onClick={handleAdd}>追加</button>
      <ul>
        {array.map((item) => {
          return <li key={item}>{item}</li>
        })}
      </ul>

      <Main page="index"></Main>
      {/* <Facebooks /> */}
      <Footer />

    </div>
  );
}
