import Head from 'next/head';
import Image from 'next/image';
import styles from 'src/styles/Home.module.css';
import { Footer } from 'src/components/Footer';
import { Main } from 'src/components/Main';
import { Facebooks } from 'src/components/Facebooks';
import { Header } from 'src/components/Header';
import { useEffect,useState,useCallback } from 'react';

export default function Home() {
  //配列分割代入
  const [item , setItem ] = useState(1);

  const handleClick =  useCallback((e) => {
    if(item<10){
      setItem((item) => item +1);
    }
    // setItem((item) => item +1);
  },[item]);

  useEffect(() =>{
    // console.log("マウント時");
    document.body.style.backgroundColor = "lightblue";

    return ()=>{
      // console.log("アンマウント時");
      document.body.style.backgroundColor = "";
    }
  },[]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Study Index</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <h1>{item}</h1>

      <button onClick={handleClick}>ボタン</button>

      <Main page="index"></Main>
      {/* <Facebooks /> */}
      <Footer />

    </div>
  );
}
