import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Footer } from '../components/Footer';
import { Main } from '../components/Main';
import { Facebooks } from '../components/Facebooks';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Study Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main page="index"></Main>

      {/* <Facebooks /> */}

      <Footer />

    </div>
  )
}
